class LayerStyle {
    constructor(s) {
        this.style = [
            s.fillColor,
            s.fillOpacity,
            s.strokeColor,
            s.strokeDashStyle,
            s.strokeOpacity,
            s.strokeWidth
        ];
    }
}

let layerStyles = new function () {
    this.styleMap = new Map([
        ['default', new LayerStyle({ fillColor: 'red', strokeColor: 'black', strokeOpacity: 1, strokeWidth: 1, strokeDashstyle: 'solid' })],
        ['Aquatoria_polygons', new LayerStyle({ fillColor: '#B0C4DE' })],
        ['OblastSateliteTV_polygons', new LayerStyle({ fillColor: '#FFE4C4', fillOpacity: 0.5 })],
        ['border_munic_polygons', new LayerStyle({ fillColor: 'orange' })],
        ['land_lease_cx_polygons', new LayerStyle({ fillColor: 'slategrey' })],
        ['mreb_oz_polygons', new LayerStyle({ fillColor: 'blue' })],
        ['mreb_polygons', new LayerStyle({ fillColor: 'green' })],
        ['MREB_border_fireforce_polygons', new LayerStyle({ fillColor: 'Yellow' })],
        ['MREB_border_fireforce_grazh_polygons', new LayerStyle({ fillColor: 'peru' })],
        ['MREB_border_fireforce_fed_polygons', new LayerStyle({ fillColor: '#FF0000' })],
        ['MREB_border_fireforce_ved_polygons', new LayerStyle({ fillColor: '#4169E1' })],
        ['MREB_border_fireforce_dobr_polygons', new LayerStyle({ fillColor: '#00FA9A' })],
        ['MREB_border_fireforce_mun_polygons', new LayerStyle({ fillColor: '#87CEFA' })],
        ['MREB_border_fireforce_chast_polygons', new LayerStyle({ fillColor: '#8A2BE2' })],
        ['added_lines', new LayerStyle({ strokeColor: 'red' })],
        ['added_polygons', new LayerStyle({ fillColor: 'blue' })],
        ['Heating_system_lines', new LayerStyle({ strokeColor: 'red' })],
        ['Water_system_lines', new LayerStyle({ strokeColor: 'blue' })],
        ['Power_network_lines', new LayerStyle({ strokeColor: 'yellow' })],
        ['sanitar_zone1_polygons', new LayerStyle({ fillColor: '#98FB98' })],
        ['sanitar_zone2_polygons', new LayerStyle({ fillColor: '#98FB98' })],
        ['sanitar_zone3_polygons', new LayerStyle({ fillColor: '#98FB98' })],
        ['minimus_polygons', new LayerStyle({ fillColor: '#EEDD82' })],
        ['license_opi_polygons', new LayerStyle({ fillColor: '#EEDD82' })],
        ['undeground_water_drink_polygons', new LayerStyle({ fillColor: '#5F9EA0' })],
        ['canal_Rostelek_indefin_lines', new LayerStyle({ strokeColor: '#5A009D', strokeDashStyle: 'solid' })],
        ['canal_Rostelek_remrec_lines', new LayerStyle({ strokeColor: '#FF0000', strokeDashStyle: 'solid' })],
        ['canal_Rostelek_work_lines', new LayerStyle({ strokeColor: '#00FF00', strokeDashStyle: 'solid' })],
        ['Gos_sobstv_to_privatiz_polygons', new LayerStyle({ fillColor: '#556B2F' })],
        ['Gos_mun_sobstv_polygons', new LayerStyle({ fillColor: '#556B2F' })],
        ['vacant_land_polygons', new LayerStyle({ fillColor: '#778899' })],
        ['bus_transmun_route_lines', new LayerStyle({ strokeColor: '#CD5C5C' })],
        ['bus_city_rout_lines', new LayerStyle({ strokeColor: '#228B22' })],
        ['Gasoprovod_lines', new LayerStyle({ strokeColor: '#ADD8E6' })],
        ['invest_objects_polygons', new LayerStyle({ fillColor: '#00FF7F' })],
        ['investment_proposals_polygons', new LayerStyle({ fillColor: '#FFA500' })],
        ['mintarif2016_8_lines', new LayerStyle({ strokeColor: '#008B45' })],
        ['mintarif2016_9_lines', new LayerStyle({ strokeColor: '#FF00FF' })],
        ['mintarif2016_10_lines', new LayerStyle({ strokeColor: '#FF0000' })],
        ['mintarif2016_2_lines', new LayerStyle({ strokeColor: '#0000CD' })],
        ['mintarif2016_3_polygons', new LayerStyle({ fillColor: '#008B45', fillOpacity: 0.4, strokeColor: '#008B00', strokeOpacity: 1 })],
        ['mintarif2016_11_polygons', new LayerStyle({ fillColor: '#00E5EE', fillOpacity: 0.4, strokeColor: '#00868B', strokeOpacity: 1 })],
        ['shos_briks_marshruty_lines', new LayerStyle({ strokeColor: '#2F4F4F', strokeOpacity: 0.4 })],
        ['Autoroad_lines', new LayerStyle({ strokeColor: '#FFD700', strokeOpacity: 0.4 })],
        ['VOLS_MTC_lines', new LayerStyle({ strokeColor: '#FF0000' })],
        ['VOLS_TTK_MR_SU_lines', new LayerStyle({ strokeColor: '#CD2626' })],
        ['VOLS_PAO_CHMK_lines', new LayerStyle({ strokeColor: '#708090' })],
        ['VOLS_OOO_NEW_TECHNO_CONNECT_lines', new LayerStyle({ strokeColor: '#00E5EE' })],
        ['VOLS_ZAO_INSIT_INVEST_lines', new LayerStyle({ strokeColor: '#8B4513' })],
        ['VOLS_OOO_Ekran_TV_lines', new LayerStyle({ strokeColor: '#4169E1' })],
        ['VOLS_TELE2_lines', new LayerStyle({ strokeColor: '#000000' })],
        ['VOLS_DOM_RU_lines', new LayerStyle({ strokeColor: '#B22222' })],
        ['license_water_2017_polygons', new LayerStyle({ strokeColor: 'Blue', strokeOpacity: 0.5 })],
        ['VOLS_abonent_1_lines', new LayerStyle({ strokeColor: '#FF00FF' })],
        ['VOLS_abonent_2_lines', new LayerStyle({ strokeColor: '#800080' })],
        ['VOLS_abonent_3_lines', new LayerStyle({ strokeColor: '#FF0000' })],
        ['VOLS_abonent_4_lines', new LayerStyle({ strokeColor: '#800000' })],
        ['VOLS_abonent_5_lines', new LayerStyle({ strokeColor: '#FFFF00' })],
        ['VOLS_abonent_6_lines', new LayerStyle({ strokeColor: '#808000' })],
        ['VOLS_abonent_7_lines', new LayerStyle({ strokeColor: '#00FF00' })],
        ['VOLS_abonent_8_lines', new LayerStyle({ strokeColor: '#008000' })],
        ['VOLS_abonent_9_lines', new LayerStyle({ strokeColor: '#00FFFF' })],
        ['VOLS_abonent_10_lines', new LayerStyle({ strokeColor: '#008080' })],
        ['VOLS_abonent_11_lines', new LayerStyle({ strokeColor: '#808000' })],
        ['VOLS_abonent_12_lines', new LayerStyle({ strokeColor: '#00FF00' })],
        ['VOLS_abonent_13_lines', new LayerStyle({ strokeColor: '#1E90FF' })],
        ['VOLS_abonent_14_lines', new LayerStyle({ strokeColor: '#00FA9A' })],
        ['VOLS_abonent_15_lines', new LayerStyle({ strokeColor: '#FF4500' })],
        ['VOLS_abonent_16_lines', new LayerStyle({ strokeColor: '#FF8C00' })],
        ['VOLS_abonent_17_lines', new LayerStyle({ strokeColor: '#8B0000' })],
        ['VOLS_abonent_18_lines', new LayerStyle({ strokeColor: '#4B0082' })],
        ['VOLS_abonent_19_lines', new LayerStyle({ strokeColor: '#6A5ACD' })],
        ['VOLS_abonent_20_lines', new LayerStyle({ strokeColor: '#483D8B' })],
        ['VOLS_abonent_21_lines', new LayerStyle({ strokeColor: '#FF00FF' })],
        ['VOLS_abonent_22_lines', new LayerStyle({ strokeColor: '#800080' })],
        ['VOLS_abonent_23_lines', new LayerStyle({ strokeColor: '#FF0000' })],
        ['VOLS_abonent_24_lines', new LayerStyle({ strokeColor: '#800000' })],
        ['VOLS_abonent_25_lines', new LayerStyle({ strokeColor: '#FFFF00' })],
        ['VOLS_abonent_26_lines', new LayerStyle({ strokeColor: '#808000' })],
        ['VOLS_abonent_27_lines', new LayerStyle({ strokeColor: '#00FF00' })],
        ['VOLS_abonent_28_lines', new LayerStyle({ strokeColor: '#008000' })],
        ['VOLS_abonent_29_lines', new LayerStyle({ strokeColor: '#00FFFF' })],
        ['VOLS_abonent_30_lines', new LayerStyle({ strokeColor: '#008080' })],
        ['VOLS_abonent_31_lines', new LayerStyle({ strokeColor: '#808000' })],
        ['VOLS_abonent_32_lines', new LayerStyle({ strokeColor: '#00FF00' })],
        ['VOLS_abonent_33_lines', new LayerStyle({ strokeColor: '#1E90FF' })],
        ['VOLS_abonent_34_lines', new LayerStyle({ strokeColor: '#00FA9A' })],
        ['VOLS_abonent_35_lines', new LayerStyle({ strokeColor: '#FF4500' })],
        ['VOLS_abonent_36_lines', new LayerStyle({ strokeColor: '#FF8C00' })],
        ['VOLS_abonent_37_lines', new LayerStyle({ strokeColor: '#8B0000' })],
        ['VOLS_abonent_38_lines', new LayerStyle({ strokeColor: '#4B0082' })],
        ['VOLS_abonent_39_lines', new LayerStyle({ strokeColor: '#6A5ACD' })],
        ['VOLS_abonent_40_lines', new LayerStyle({ strokeColor: '#483D8B' })],
        ['VOLS_abonent_41_lines', new LayerStyle({ strokeColor: '#FF00FF' })],
        ['VOLS_abonent_42_lines', new LayerStyle({ strokeColor: '#800080' })],
        ['VOLS_abonent_43_lines', new LayerStyle({ strokeColor: '#FF0000' })],
        ['VOLS_abonent_44_lines', new LayerStyle({ strokeColor: '#800000' })],
        ['VOLS_abonent_45_lines', new LayerStyle({ strokeColor: '#FFFF00' })],
        ['VOLS_abonent_46_lines', new LayerStyle({ strokeColor: '#808000' })],
        ['VOLS_abonent_47_lines', new LayerStyle({ strokeColor: '#00FF00' })],
        ['VOLS_abonent_48_lines', new LayerStyle({ strokeColor: '#008000' })],
        ['VOLS_abonent_49_lines', new LayerStyle({ strokeColor: '#00FFFF' })],
        ['VOLS_abonent_50_lines', new LayerStyle({ strokeColor: '#008080' })],
        ['VOLS_abonent_51_lines', new LayerStyle({ strokeColor: '#808000' })],
        ['VOLS_abonent_52_lines', new LayerStyle({ strokeColor: '#00FF00' })],
        ['VOLS_abonent_53_lines', new LayerStyle({ strokeColor: '#1E90FF' })],
        ['VOLS_abonent_54_lines', new LayerStyle({ strokeColor: '#00FA9A' })],
        ['VOLS_abonent_55_lines', new LayerStyle({ strokeColor: '#FF4500' })],
        ['VOLS_abonent_56_lines', new LayerStyle({ strokeColor: '#FF8C00' })],
        ['VOLS_abonent_57_lines', new LayerStyle({ strokeColor: '#8B0000' })],
        ['VOLS_abonent_58_lines', new LayerStyle({ strokeColor: '#4B0082' })],
        ['VOLS_abonent_59_lines', new LayerStyle({ strokeColor: '#6A5ACD' })],
        ['VOLS_abonent_60_lines', new LayerStyle({ strokeColor: '#483D8B' })],
        ['FootPath_Good_lines', new LayerStyle({ strokeColor: '#00CD00' })],
        ['FootPath_Poor_lines', new LayerStyle({ strokeColor: '#FF0000' })],
        ['road_reg_mun_2020_lines', new LayerStyle({ strokeColor: '#708090' })],
        ['Green_spaces_polygons', new LayerStyle({ fillColor: '#00FF7F', fillOpacity: 0.4, strokeColor: '#00FF7F', strokeOpacity: 1 })],
        ['Community_work_day_on_water_polygons', new LayerStyle({ fillColor: '#FFFF00', fillOpacity: 0.4, strokeColor: '#FFFF00', strokeOpacity: 1 })],
        ['rayony_gor_chel_polygons', new LayerStyle({ fillColor: '#708090', fillOpacity: 0.15, strokeColor: '#323232', strokeOpacity: 0.75 })],
        ['chelyabinsk_townships_2020_09_07_polygons', new LayerStyle({ fillColor: '#708090', fillOpacity: 0.15, strokeColor: '#323232', strokeOpacity: 0.75 })],
        ['HighWay_lines', new LayerStyle({ strokeColor: '#000080', strokeWidth: 1.2 })],
        ['Intra-district_territ_lines', new LayerStyle({ strokeColor: '#FFFF00', strokeWidth: 1.5 })],
        ['Intra-yard_territ_lines', new LayerStyle({ strokeColor: '#FF0000', strokeWidth: 1.5 })],
        ['VOLS_intersvyaz_lines', new LayerStyle({ strokeColor: '#264796', strokeWidth: 1.5 })],
        ['invest_objects_polygons', new LayerStyle({ fillColor: '#228b22', fillOpacity: 0.4, strokeColor: '#228b22', strokeOpacity: 1 })],
        ['investment_proposals_polygons', new LayerStyle({ fillColor: '#4682b4', fillOpacity: 0.4, strokeColor: '#4682b4', strokeOpacity: 1 })],
        ['Gos_mun_sobstv_polygons', new LayerStyle({ fillColor: '#f08080', fillOpacity: 0.4, strokeColor: '#f08080', strokeOpacity: 1 })],
        ['vacant_land_polygons', new LayerStyle({ fillColor: '#8fbc8f', fillOpacity: 0.4, strokeColor: '#8fbc8f', strokeOpacity: 1 })],
        ['net_chel_go_250x250_polygons', new LayerStyle({ fillColor: '#8fbc8f', fillOpacity: 0.4, strokeColor: '#8fbc8f', strokeOpacity: 0.1 })],
        ['net_chel_go_250_250_polygons', new LayerStyle({ fillColor: '#8fbc8f', fillOpacity: 0.4, strokeColor: '#8fbc8f', strokeOpacity: 0.1 })],
        ['noctv_yesatv_2018_polygons', new LayerStyle({ fillColor: '#8fbc8f', fillOpacity: 0.4, strokeColor: '#8fbc8f', strokeOpacity: 0.1 })],
        ['local_net_chgo_250_250_4326_polygons', new LayerStyle({ fillColor: 'mediumblue', fillOpacity: 0.15, strokeColor: 'mediumblue', strokeOpacity: 0.2 })],
        ['rosreestr_test_polygons', new LayerStyle({ fillColor: 'blue', fillOpacity: 0.5, strokeColor: 'blue', strokeOpacity: 0.2 })],
        ['rosreestr_zdanie_polygons', new LayerStyle({ fillColor: 'blue', fillOpacity: 0.5, strokeColor: 'blue', strokeOpacity: 0.2 })],
        ['borders_mun_2021_polygons', new LayerStyle({ fillColor: 'cadetblue', fillOpacity: 0.7, strokeColor: 'blue', strokeOpacity: 0.2 })],
        ['border_Chel_obl_polygons', new LayerStyle({ fillColor: 'red', fillOpacity: 0.5, strokeColor: 'red', strokeOpacity: 0.2 })],
        ['border_TOSER_polygons', new LayerStyle({ fillColor: 'yellow', fillOpacity: 0.25, strokeColor: 'yellow', strokeOpacity: 0.2 })],
        ['rr_buildings_brown_polygons', new LayerStyle({ fillColor: 'blue', fillOpacity: 0.5, strokeColor: 'blue', strokeOpacity: 0.2 })],
        ['rr_zu_green_polygons', new LayerStyle({ fillColor: 'blue', fillOpacity: 0.5, strokeColor: 'blue', strokeOpacity: 0.2 })],
        ['regmun_roads_2021_lines', new LayerStyle({ strokeColor: '#708090' })],
        ['kategory_road2021_lines', new LayerStyle({ strokeColor: 'orange' })]
    ]);
    this.extract = function (name) {
        return (this.styleMap.has(name) ? this.styleMap.get(name).style : this.styleMap.get('default').style);
    };
};