switch (wfsNameWithoutPrefix) {
    case 'Aquatoria_polygons': fillColor = '#B0C4DE'; break;
    case 'OblastSateliteTV_polygons': fillColor = '#FFE4C4'; fillOpacity = 0.5; break;
    case 'border_munic_polygons': fillColor = 'orange'; break;
    case 'land_lease_cx_polygons': fillColor = 'slategrey'; break;
    case 'mreb_oz_polygons': fillColor = 'blue'; break;
    case 'mreb_polygons': fillColor = 'green'; break;
    case 'MREB_border_fireforce_polygons': fillColor = 'Yellow'; break;
    case 'MREB_border_fireforce_grazh_polygons': fillColor = 'peru'; break;
    case 'MREB_border_fireforce_fed_polygons': fillColor = '#FF0000'; break;
    case 'MREB_border_fireforce_ved_polygons': fillColor = '#4169E1'; break;
    case 'MREB_border_fireforce_dobr_polygons': fillColor = '#00FA9A'; break;
    case 'MREB_border_fireforce_mun_polygons': fillColor = '#87CEFA'; break;
    case 'MREB_border_fireforce_chast_polygons': fillColor = '#8A2BE2'; break;
    case 'added_lines': strokeColor = 'red'; break;
    case 'added_polygons': fillColor = 'blue'; break;
    case 'Heating_system_lines': strokeColor = 'red'; break;
    case 'Water_system_lines': strokeColor = 'blue'; break;
    case 'Power_network_lines': strokeColor = 'yellow'; break;
    case 'sanitar_zone1_polygons':
    case 'sanitar_zone2_polygons':
    case 'sanitar_zone3_polygons': fillColor = '#98FB98'; break;
    case 'minimus_polygons':
    case 'license_opi_polygons': fillColor = '#EEDD82'; break;
    case 'undeground_water_drink_polygons': fillColor = '#5F9EA0'; break;
    case 'canal_Rostelek_indefin_lines': strokeColor = '#5A009D'; strokeDashstyle = 'solid'; break;
    case 'canal_Rostelek_remrec_lines': strokeColor = '#FF0000'; strokeDashstyle = 'solid'; break;
    case 'canal_Rostelek_work_lines': strokeColor = '#00FF00'; strokeDashstyle = 'solid'; break;
    case 'Gos_sobstv_to_privatiz_polygons': fillColor = '#556B2F'; break;
    case 'Gos_mun_sobstv_polygons': fillColor = '#556B2F'; break;
    case 'vacant_land_polygons': fillColor = '#778899'; break;
    case 'bus_transmun_route_lines': strokeColor = '#CD5C5C'; break;
    case 'bus_city_rout_lines': strokeColor = '#228B22'; break;
    case 'Gasoprovod_lines': strokeColor = '#ADD8E6'; break;
    case 'invest_objects_polygons': fillColor = '#00FF7F'; break;
    case 'investment_proposals_polygons': fillColor = '#FFA500'; break;
    case 'mintarif2016_8_lines': strokeColor = '#008B45'; break;
    case 'mintarif2016_9_lines': strokeColor = '#FF00FF'; break;
    case 'mintarif2016_10_lines': strokeColor = '#FF0000'; break;
    case 'mintarif2016_2_lines': strokeColor = '#0000CD'; break;
    case 'mintarif2016_3_polygons': fillColor = '#008B45'; fillOpacity = 0.4; strokeColor = '#008B00'; strokeOpacity = 1; break;
    case 'mintarif2016_11_polygons': fillColor = '#00E5EE'; fillOpacity = 0.4; strokeColor = '#00868B'; strokeOpacity = 1; break;
    case 'shos_briks_marshruty_lines': strokeColor = '#2F4F4F'; strokeOpacity = 0.4; break;
    case 'Autoroad_lines': strokeColor = '#FFD700'; strokeOpacity = 0.4; break;
    case 'VOLS_MTC_lines': strokeColor = '#FF0000'; break;
    case 'VOLS_TTK_MR_SU_lines': strokeColor = '#CD2626'; break;
    case 'VOLS_PAO_CHMK_lines': strokeColor = '#708090'; break;
    case 'VOLS_OOO_NEW_TECHNO_CONNECT_lines': strokeColor = '#00E5EE'; break;
    case 'VOLS_ZAO_INSIT_INVEST_lines': strokeColor = '#8B4513'; break;
    case 'VOLS_OOO_Ekran_TV_lines': strokeColor = '#4169E1'; break;
    case 'VOLS_TELE2_lines': strokeColor = '#000000'; break;
    case 'VOLS_DOM_RU_lines': strokeColor = '#B22222'; break;
    case 'license_water_2017_polygons': strokeColor = 'Blue'; strokeOpacity = 0.5; break;
    case 'VOLS_abonent_1_lines': strokeColor = '#FF00FF'; break;
    case 'VOLS_abonent_2_lines': strokeColor = '#800080'; break;
    case 'VOLS_abonent_3_lines': strokeColor = '#FF0000'; break;
    case 'VOLS_abonent_4_lines': strokeColor = '#800000'; break;
    case 'VOLS_abonent_5_lines': strokeColor = '#FFFF00'; break;
    case 'VOLS_abonent_6_lines': strokeColor = '#808000'; break;
    case 'VOLS_abonent_7_lines': strokeColor = '#00FF00'; break;
    case 'VOLS_abonent_8_lines': strokeColor = '#008000'; break;
    case 'VOLS_abonent_9_lines': strokeColor = '#00FFFF'; break;
    case 'VOLS_abonent_10_lines': strokeColor = '#008080'; break;
    case 'VOLS_abonent_11_lines': strokeColor = '#808000'; break;
    case 'VOLS_abonent_12_lines': strokeColor = '#00FF00'; break;
    case 'VOLS_abonent_13_lines': strokeColor = '#1E90FF'; break;
    case 'VOLS_abonent_14_lines': strokeColor = '#00FA9A'; break;
    case 'VOLS_abonent_15_lines': strokeColor = '#FF4500'; break;
    case 'VOLS_abonent_16_lines': strokeColor = '#FF8C00'; break;
    case 'VOLS_abonent_17_lines': strokeColor = '#8B0000'; break;
    case 'VOLS_abonent_18_lines': strokeColor = '#4B0082'; break;
    case 'VOLS_abonent_19_lines': strokeColor = '#6A5ACD'; break;
    case 'VOLS_abonent_20_lines': strokeColor = '#483D8B'; break;
    case 'VOLS_abonent_21_lines': strokeColor = '#FF00FF'; break;
    case 'VOLS_abonent_22_lines': strokeColor = '#800080'; break;
    case 'VOLS_abonent_23_lines': strokeColor = '#FF0000'; break;
    case 'VOLS_abonent_24_lines': strokeColor = '#800000'; break;
    case 'VOLS_abonent_25_lines': strokeColor = '#FFFF00'; break;
    case 'VOLS_abonent_26_lines': strokeColor = '#808000'; break;
    case 'VOLS_abonent_27_lines': strokeColor = '#00FF00'; break;
    case 'VOLS_abonent_28_lines': strokeColor = '#008000'; break;
    case 'VOLS_abonent_29_lines': strokeColor = '#00FFFF'; break;
    case 'VOLS_abonent_30_lines': strokeColor = '#008080'; break;
    case 'VOLS_abonent_31_lines': strokeColor = '#808000'; break;
    case 'VOLS_abonent_32_lines': strokeColor = '#00FF00'; break;
    case 'VOLS_abonent_33_lines': strokeColor = '#1E90FF'; break;
    case 'VOLS_abonent_34_lines': strokeColor = '#00FA9A'; break;
    case 'VOLS_abonent_35_lines': strokeColor = '#FF4500'; break;
    case 'VOLS_abonent_36_lines': strokeColor = '#FF8C00'; break;
    case 'VOLS_abonent_37_lines': strokeColor = '#8B0000'; break;
    case 'VOLS_abonent_38_lines': strokeColor = '#4B0082'; break;
    case 'VOLS_abonent_39_lines': strokeColor = '#6A5ACD'; break;
    case 'VOLS_abonent_40_lines': strokeColor = '#483D8B'; break;
    case 'VOLS_abonent_41_lines': strokeColor = '#FF00FF'; break;
    case 'VOLS_abonent_42_lines': strokeColor = '#800080'; break;
    case 'VOLS_abonent_43_lines': strokeColor = '#FF0000'; break;
    case 'VOLS_abonent_44_lines': strokeColor = '#800000'; break;
    case 'VOLS_abonent_45_lines': strokeColor = '#FFFF00'; break;
    case 'VOLS_abonent_46_lines': strokeColor = '#808000'; break;
    case 'VOLS_abonent_47_lines': strokeColor = '#00FF00'; break;
    case 'VOLS_abonent_48_lines': strokeColor = '#008000'; break;
    case 'VOLS_abonent_49_lines': strokeColor = '#00FFFF'; break;
    case 'VOLS_abonent_50_lines': strokeColor = '#008080'; break;
    case 'VOLS_abonent_51_lines': strokeColor = '#808000'; break;
    case 'VOLS_abonent_52_lines': strokeColor = '#00FF00'; break;
    case 'VOLS_abonent_53_lines': strokeColor = '#1E90FF'; break;
    case 'VOLS_abonent_54_lines': strokeColor = '#00FA9A'; break;
    case 'VOLS_abonent_55_lines': strokeColor = '#FF4500'; break;
    case 'VOLS_abonent_56_lines': strokeColor = '#FF8C00'; break;
    case 'VOLS_abonent_57_lines': strokeColor = '#8B0000'; break;
    case 'VOLS_abonent_58_lines': strokeColor = '#4B0082'; break;
    case 'VOLS_abonent_59_lines': strokeColor = '#6A5ACD'; break;
    case 'VOLS_abonent_60_lines': strokeColor = '#483D8B'; break;
    case 'FootPath_Good_lines': strokeColor = '#00CD00'; break;
    case 'FootPath_Poor_lines': strokeColor = '#FF0000'; break;
    case 'road_reg_mun_2020_lines': strokeColor = '#708090'; break;
    case 'Green_spaces_polygons': fillColor = '#00FF7F'; fillOpacity = 0.4; strokeColor = '#00FF7F'; strokeOpacity = 1; break;
    case 'Community_work_day_on_water_polygons': fillColor = '#FFFF00'; fillOpacity = 0.4; strokeColor = '#FFFF00'; strokeOpacity = 1; break;
    case 'rayony_gor_chel_polygons': fillColor = '#708090'; fillOpacity = 0.15; strokeColor = '#323232'; strokeOpacity = 0.75; break;
    case 'chelyabinsk_townships_2020_09_07_polygons': fillColor = '#708090'; fillOpacity = 0.15; strokeColor = '#323232'; strokeOpacity = 0.75; break;
    case 'HighWay_lines': strokeColor = '#000080'; strokeWidth = 1.2; break;
    case 'Intra-district_territ_lines': strokeColor = '#FFFF00'; strokeWidth = 1.5; break;
    case 'Intra-yard_territ_lines': strokeColor = '#FF0000'; strokeWidth = 1.5; break;
    case 'VOLS_intersvyaz_lines': strokeColor = '#264796'; strokeWidth = 1.5; break;
    default: break;
}